### ISSUE TITLE
Need Discourse Page for site

### ISSUE THREAD

**Issue by MateoDev** [wgmi-community/website#6]
### Summary
We need a central hub where the community can view indexed issues in the community and that they can comment on them. This would be helpful place to post proposals for electing members for roles, proposals for community-wide improvements, posting any community updates that require discussion prior to governance voting.

Categories: 
- General
- Proposals 
- Community 
- Feedback

**Clone:** 
https://github.com/discourse/discourse

**Comment by harishkotra** [comment]
@MateoDev will need to decided on the sub-domain to host this. 

Since we have wgmi.community, I don't think we should do community.wgmi.community. Do you think we should do forum.wgmi.community or space.wgmi.community? Any other ideas that you have?

**Comment by MateoDev** [comment]
@harishkotra let's do forum.wgmi.community. That sounds perfect. Totally agree with you.

**Comment by harishkotra** [comment]
Done. Discourse forums are now live at https://forum.wgmi.community
